### ISSUE TITLE
ENH: Configuration outside of TS

### ISSUE THREAD

**Issue by aronwk-aaron** [MasterTemple/LEGO-Universe-Discord-Bot#8]
Having the configuration outside of TS would allow for easier shipping and deployment of the bot for end users, as you could provide/ship a release package or a docker container running in the environment that it needs (node 16+) and the end user wouldn't need to worry about that

**Comment by MasterTemple** [comment]
The bot now uses a .env config file and no longer requires transpiling when the config is changed.
